export const URLS = {
    BASE_URL_EXPORT: "http://127.0.0.1:8000",
    USER_LOGIN_URL: "/users/admin-login/",
    USER_REGISTER_URL: "/authentication/register/",
    GET_AGENCY_LIST_URL: "/document/agency-list/",
    ADD_CATEGORY_URL: "/expense/category/",
    EXPENSE_ITEM_SETUP_URL: "/expense/expenseitemsetup/",
    UPDATE_EXPENSE_ITEM_SETUP_URL: "/expense/expenseitemsetup/",
    GET_ACCOUNTING_CODE_URL: "/expense/accountingcode/",
    EXPENSE_TYPE_URL: "/expense/expensetype/",
    UPDATE_USER_PROFILE_URL: "/users/profile-update/",
    EXTERNAL_ACCOUNT_CODE_URL: "/expense/externalaccountcode/",
    ADD_USER_URL: "/users/create_user/",
    ITEMIZATION_SUBMIT_URL: "/expense/expenseitemization/",
    GET_EXPENSE_PANEL_URL: "/expense/expense-list/",
    ADD_EXPENSE_URL: "/expense/add_expense/",
    ADD_REPORT_URL: "/expense/expensereport/",
    GET_REPORT_LIST_URL:"/expense/expensereport/",
    UPDATE_REPORT: "/expense/expensereport/",
    GET_ROLE_URL: "/roles/role/",
    GET_MANAGER_LIST_URL: "/users/get_users/",
    EXPENSE_TYPE_PANEL_URL: "/expense/expensetypelist/",
    EXTERNAL_ACCOUNT_CODE_PANEL_URL: "/expense/externalaccount-code-list/",
    UPDATE_ABOUTUS_URL: "/users/about_us/",
    UPDATE_CONTACTUS_URL: "/users/contact_us/",
    UPDATE_PASSWORD_URL: "/users/change-password/",
    GET_COMPANY_LIST_URL: "/users/company-list/",
    DELETE_COMPANY_LIST_URL : "/authentication/delete_company/",
    UPDATE_COMPANY_LIST_URL: "/authentication/update_company/",
    GET_EXPENSE_ITEM_SETUP_PANEL_URL: "/expense/expense-item-setup-list/",
    GET_ITEMIZATION_PANEL_URL: "/expense/expense-itemization-list/",
    GET_ACCOUNTINGCODE_PANEL_URL: "/expense/accounting-code-list/",
    GET_CATEGORY_PANEL_URL: "/expense/category-list/",
    APPLY_CARD_URL: "/card/apply_card/",
    UPDATE_ACCOUNTING_CODE_URL: "/expense/accountingcode/",
    UPDATE_CATEGORY_PANEL_URL: "/expense/category/",
    UPDATE_EXPENSEITEMIZATION_PANEL_URL: "/expense/expenseitemization/",
    UPDATE_EXPENSE_PANEL_URL: "/expense/edit_expense/",
    EXPENSETABLE_SUBMIT_TRUE_URL: "/expense/submit_expense/",
    UPDATE_EXPENSE_TYPE: "/expense/expensetype/",
    UPDATE_USER: "/users/edit_user/",
    EXPENSE_APPROVED_MANEGER_URL: "/expense/expense-approve/",
    EXPENSE_REJECT_MANAGER_URL: "/expense/expense-reject/",
    EXPENSE_HOLD_MANGER_URL: "/expense/expense-hold/",
    EXPORTBUTTON_ACCOUNTING_CODE_URL: "/expense/accounting-code-list/",
    FINANCE_MANAGER_EXPENSE_REJECT_URL: "/expense/rejected_by_fm/",
    FINANCE_MANAGER_EXPENSE_HOLD_URL: "/expense/hold_by_fm/",
    FINANCE_MANAGER_EXPENSE_APPROVE_URL: "/expense/approved_by_fm/",
    ADD_ACCOUNT_BY_FINANCE_MANAGER_URL: "/card/add_account/",
    GET_USER_PERMISSIONS_ADD_ROLE_URL: "/users/permissions_get/",
    GET_USER_PERMISSIONS_LIST_ADD_ROLE: "/users/permissions_list/",
    ROLE_COMMON_URL: "/roles/role/",
    GET_EMPLOYEE_ACCOUNTNO_URL: "/card/get_user_account/",
    GET_EXPENSE_LIST_FINANCE_MANAGER_URL:"/expense/expense-list-finance-manager/",
    GET_FINANCE_MANAGER_LIST_URL: "/users/get-account-managers/",
    GET_MANEGERAPPROVED_LIST_URL: "expense/expense-list-manager/",
    OWN_EXPENSE_DRAFT_URL: "/expense/drafted_expense/",
    OWN_EXPENSE_REJECT_URL: "/expense/rejected_expense/",
    OWN_EXPENSE_HOLD_URL: "/expense/hold_expense/",
    DELETE_USER_URL: "/users/delete-user/",
    MANAGER_CARD_APPROVED_LIST_URL:"/expense/approval_expense-list-manager/",
    MANAGER_CARD_REJECT_LIST_URL:"/expense/rejected_expense-list-manager/",
    MANAGER_CARD_HOLD_LIST_URL:"/expense/hold_expense-list-manager/",
    OWN_EXPENSE_APPROVE_URL:"/expense/approval_expense/", 
  };
  